name = "youtick-livepeer-bridge"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
LIVEPEER_BRIDGE_ENABLED = "false"
LIVEPEER_NEAR_CREATOR_FEE_ENABLED = "false"

[version_metadata]
binding = "CF_VERSION_METADATA"

[[durable_objects.bindings]]
name = "LIVEPEER_CONTROL"
class_name = "LivepeerControl"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LivepeerControl"]
